---
title: "Lab 2"
author: "Min Zhang, Hana Lee, Joshua Budi"
date: "2/20/2019"
output: html_document
---

```{r results='hide', message=FALSE, warning=FALSE} 
install.packages("sf")
library(sf)
install.packages("tidyverse")
library(tidyverse)
library(purrr)
library(ggplot2)
install.packages("ggspatial")
library(ggspatial)

```


```{r results='hide'}
p <- ggplot() +
  geom_sf(data = read_sf("data/ME-GIS/Coastline2.shp"), 
          colour="grey10", fill="grey90") +
  geom_sf(data = read_sf("data/ME-GIS/Rivers19.shp"), 
          colour="steelblue", size=0.3) +
  geom_sf(data = read_sf("data/ME-GIS/PrimaryRoads.shp"), 
          size = 0.7, colour="grey30") +
  geom_sf(data = read_sf("data/ME-GIS/Cities.shp")) +
  annotation_scale(location="bl") +
  annotation_north_arrow(location="br")+ 
  geom_sf_text(data=read_sf("data/ME-GIS/Cities.shp"),mapping=aes(label=Name))+
  theme_bw()

ggsflabel::geom_sf_label_repel
ggrepel
```

```{r}
p
```

```{r results='hide'}
q <- ggplot()+
  geom_sf_text(mapping=aes)
```

